.gitignore, README.cs.md, README.md
**Changes**
- Added english version of README as `README.md`, czech version is now under `README.cs.md`
- Added `.vscode/` to `.gitignore`
Someone with better language skills than me should check this
=> Translation of README.md to EN

src/Inkluzitron/Extensions/TimeSpanExtensions.cs, src/Inkluzitron/Modules/SystemModule.cs
Implementace příkazu pro zjištění, jak dlouho běží bot. Jen s lepší hláškou, jak rubbergod.
Resolved #13
=> Implementace příkazu uptime.

src/Inkluzitron/Modules/ReplyModule.cs, src/Inkluzitron/appsettings.json
+ jsem dočasně fixnul ten `ReplyAsync` u automatických odpovědí
=> Oprava emotů na produkčním serveru

src/Inkluzitron/Modules/ReplyModule.cs
Regex kontroluje, jestli se fráze náhodou nenachází uprostřed jiného slova
(negative lookahead a lookbehind)
=> Robustnější matchování automatických zpráv

src/Inkluzitron/Handlers/CommandsHandler.cs, src/Inkluzitron/Modules/ImagesModule.cs, src/Inkluzitron/Modules/MockingModule.cs, src/Inkluzitron/Modules/ModuleBase.cs
- Alias pro spank-harder
- Opravy nefunkčnosti DMs
- Upozornění, že se něco nepovedlo
=> Pár menších oprav

src/Inkluzitron/Modules/MockingModule.cs
Add support for replying to author of referenced message when using `$mock` only. 
Also change mocking algorithm a bit so it changes cases on "random". Also make `L` letter always uppercase and `i` letter always lowercase for better reading.
=> Mocking update

src/Inkluzitron/Enums/DuckState.cs, src/Inkluzitron/Extensions/UserExtensions.cs, src/Inkluzitron/Models/DuckCurrentState.cs, src/Inkluzitron/Modules/DuckModule.cs, src/Inkluzitron/appsettings.json
=> Implementace příkazu pro stav kachny. Port z GrillBot.

README.cs.md, README.md, src/Inkluzitron/Extensions/CollectionExtensions.cs, src/Inkluzitron/Extensions/CommandExtensions.cs, src/Inkluzitron/Handlers/CommandsHandler.cs, src/Inkluzitron/Modules/BdsmTestOrgQuizModule.cs, src/Inkluzitron/Modules/DuckModule.cs, src/Inkluzitron/Modules/Help/HelpModule.cs, src/Inkluzitron/Modules/Help/HelpPageEmbed.cs, src/Inkluzitron/Modules/Help/HelpReactionHandler.cs, src/Inkluzitron/Modules/HolidayModule.cs, src/Inkluzitron/Modules/ImagesModule.cs, src/Inkluzitron/Modules/MockingModule.cs, src/Inkluzitron/Modules/RandomModule.cs, src/Inkluzitron/Modules/ReactionsModule.cs, src/Inkluzitron/Modules/SendModule.cs, src/Inkluzitron/Modules/SystemModule.cs
=> Implementace nápovědy

src/Inkluzitron/Enums/BdsmTraits.cs, src/Inkluzitron/Modules/BdsmTestOrg/BdsmModule.cs, src/Inkluzitron/Modules/ImagesModule.cs, src/Inkluzitron/Services/UserBdsmTraitsService.cs
* Opraven špatný název kategorie testu
* Otočení obrázku, pokud je mířený na autora
* Úprava algoritmu použití obrázků podle testů uživatelů
=> Hotfix testu + flip obrázků a úprava traits algoritmu

src/Inkluzitron/Extensions/CommandExtensions.cs, src/Inkluzitron/Handlers/CommandsHandler.cs, src/Inkluzitron/Models/UrbanApi/UrbanDefinition.cs, src/Inkluzitron/Models/UrbanApi/UrbanQueryResult.cs, src/Inkluzitron/Models/UrbanQueryResult.cs, src/Inkluzitron/Modules/Help/HelpModule.cs, src/Inkluzitron/Modules/Help/HelpPageEmbed.cs, src/Inkluzitron/Modules/Help/HelpReactionHandler.cs, src/Inkluzitron/Modules/HolidayModule.cs, src/Inkluzitron/Modules/HuggingModule.cs, src/Inkluzitron/Modules/ImagesModule.cs, src/Inkluzitron/Modules/MockingModule.cs, src/Inkluzitron/Modules/ModuleBase.cs, src/Inkluzitron/Modules/RandomModule.cs, src/Inkluzitron/Modules/RoleMenu/RoleMenuModule.cs, src/Inkluzitron/Modules/RoleMenu/RoleMenuReactionHandler.cs, src/Inkluzitron/Modules/SendModule.cs, src/Inkluzitron/Modules/SystemModule.cs, src/Inkluzitron/Modules/Urban/UrbanEmbed.cs, src/Inkluzitron/Modules/Urban/UrbanEmbedMetadata.cs, src/Inkluzitron/Modules/Urban/UrbanModule.cs, src/Inkluzitron/Services/FontService.cs, src/Inkluzitron/Services/GraphPaintingService.cs, src/Inkluzitron/appsettings.json
* Port příkazu `$urban`. Měl by fungovat podobně jako na fitwide
* Uklizeny texty nápovědy skrz všechny moduly.
* Srozumitelnější vypsání syntaxe příkazu (zvýraznění parametrů)
=> Přidání příkazu $urban a vylepšení nápovědy

src/Inkluzitron/Modules/HuggingModule.cs
Resolves #69 pro hugging module. Ostatni at si upravi sve moduly radsi sami.
=> add support for hugging user with ID

src/Inkluzitron/Enums/Gender.cs, src/Inkluzitron/Modules/UserModule.cs, src/Inkluzitron/appsettings.json
**Všechny příkazy**
**Výpis oslovení**
**Easter egg**
=> Gender na Pronouns

src/Inkluzitron/Program.cs, src/Inkluzitron/Services/LoggingService.cs, src/Inkluzitron/appsettings.json
Konec zbytečnému luštění jednořádkových řetězců výjimek.
=> Formátované logování

src/Inkluzitron/Enums/BdsmTraitOperationCheckResult.cs, src/Inkluzitron/Models/BdsmTraitOperationCheck.cs, src/Inkluzitron/Models/Settings/BdsmTraitOperationCheckTranslations.cs, src/Inkluzitron/Services/UserBdsmTraitsService.cs, src/Inkluzitron/appsettings.json
=> User not able to use whip-like commands with negative points

src/Inkluzitron/Data/BotDatabaseContext.cs, src/Inkluzitron/Data/Entities/Invite.cs, src/Inkluzitron/Handlers/InviteHandler.cs, src/Inkluzitron/Migrations/20210622133307_Invites.Designer.cs, src/Inkluzitron/Migrations/20210622133307_Invites.cs, src/Inkluzitron/Modules/InviteModule.cs, src/Inkluzitron/appsettings.json
For `$invite` command creates invite link and sends it to DMs.
For `$invite blame <user>` writes who invited that guy.
Nevim, jestli rovnou uzavrit issue na invite system, kdyz se tam resily i nejake ty veci s tou verifikaci 🤔
=> Invite module

src/Inkluzitron/Models/Settings/BotSettings.cs, src/Inkluzitron/Program.cs, src/Inkluzitron/Services/ChannelLogger/ChannelLogger.cs, src/Inkluzitron/Services/ChannelLogger/ChannelLoggerConfiguration.cs, src/Inkluzitron/Services/ChannelLogger/ChannelLoggerExtensions.cs, src/Inkluzitron/Services/ChannelLogger/ChannelLoggerProvider.cs, src/Inkluzitron/appsettings.json
=> Výpis chybových zpráv do Discord roomky

src/Inkluzitron/Modules/ReplyModule.cs
=> Change autoreply to `PR`

src/Inkluzitron/Extensions/DiscordClientExtensions.cs, src/Inkluzitron/Inkluzitron.csproj, src/Inkluzitron/Services/RuntimeService.cs, src/Inkluzitron/Services/TypeReaders/BooleanTypeReader.cs, src/Inkluzitron/Services/TypeReaders/DateTimeTypeReader.cs, src/Inkluzitron/Services/TypeReaders/EmotesTypeReader.cs, src/Inkluzitron/Services/TypeReaders/GuidTypeReader.cs, src/Inkluzitron/Services/TypeReaders/MessageTypeReader.cs, src/Inkluzitron/Services/TypeReaders/UserTypeReader.cs
Na základě #97 byl implementován nový TypeReader pro získávání uživatelů. + Pár dalších.
-  BooleanTypeReader - Kromě běžného načítání `true`/`false` přes `bool.TryParse` také dokáže udělat match na:
- `ano`/`yes`/`tru` => `true`
- `ne`/`no`/`fals` => `false`
- DateTimeTypeReader - Pokouší se načíst datum (případně čas, pokud se dobře použijí uvozovky) v lokalizacích CZ, EN a Invariant. Také umí udělat datum a čas ze slovních hodnot:
- `today`/`dnes`/`dneska` => Dnešní datum `DateTime.Today`.
- `tommorow`/`zitra`/`zítra`/`zajtra`/`zavtra` => Zítřejší datum a čas od dané chvíle.
- `včera`/`vcera`/`yesterday` => Včerejší datum a čas od dané chvíle.
- `pozítří`/`pozitri`/`pozajtra`/`poslezavtra` => Pozítří
- `teď`/`ted`/`teraz`/`zaraz` => Aktuální datum a čas.
- EmotesTypeReader - Načítá …
=> Nové čtečky datových typů pro příkazy

src/Inkluzitron/Modules/Points/PointsModule.cs
Prida info, ze za reakci na zpravu prida take 5 bodu autorovi zpravy.
=> change help message for PointsModule

src/Inkluzitron/Modules/HuggingModule.cs
Bohuzel ted diky pouziti tohoto type readeru uz nejde za `$hug <user> <user2>` pridat libovolnou zpravu, ale aspon podporuje hugovani vice uzivatelu naraz.
Closes #120
=> Added support for UserTypeReader to HuggingModule

src/Inkluzitron/Data/Entities/User.cs, src/Inkluzitron/Enums/CommandArguments/ConsentType.cs, src/Inkluzitron/Enums/CommandArguments/GrammaticalGender.cs, src/Inkluzitron/Enums/CommandArguments/PermissionAction.cs, src/Inkluzitron/Enums/CommandArguments/Pronoun.cs, src/Inkluzitron/Enums/CommandArguments/TimeSpan.cs, src/Inkluzitron/Enums/CommandConsent.cs, src/Inkluzitron/Enums/Gender.cs, src/Inkluzitron/Extensions/CommandExtensions.cs, src/Inkluzitron/Extensions/EnumExtensions.cs, src/Inkluzitron/Migrations/20210702211403_CustomPronouns.Designer.cs, src/Inkluzitron/Migrations/20210702211403_CustomPronouns.cs, src/Inkluzitron/Modules/InviteModule.cs, src/Inkluzitron/Modules/Points/PointsModule.cs, src/Inkluzitron/Modules/UserModule.cs, src/Inkluzitron/Services/UsersService.cs, src/Inkluzitron/appsettings.json
- Podpora výpisu enumu v nápovědě
- Reorganizace nastavení uživatele
- Consent předělán na obecný
- Zobrazení základních informací o uživateli
=> Podpora enumů v příkazu a informace o uživateli

src/Inkluzitron/Modules/UserModule.cs, src/Inkluzitron/appsettings.json
This reverts commit edc6bd511b4ac48dc128ec9b98ccfac3760328ee.
Nedávalo to smysl. Kdyby si někdo změnil nick, tak při další synchronizaci by mu to dalo všechny body znovu.
=> Revert "Reset data synchronizce při smazání KIS nicku"

src/Inkluzitron/Models/BdsmTraitOperationCheck.cs, src/Inkluzitron/Models/Settings/BdsmTraitOperationCheckTranslations.cs, src/Inkluzitron/Modules/SystemModule.cs, src/Inkluzitron/Services/KisService.cs, src/Inkluzitron/Services/PointsService.cs, src/Inkluzitron/Services/RuntimeService.cs, src/Inkluzitron/Utilities/FormatByValue.cs, src/Inkluzitron/appsettings.json
Pokusil jsem se o elegantnější zápis skloňování podle čísla a rodu, aby to nebylo v kódu ale ve string template.
Důležitý je to "pokusil jsem se", takže jsem otevřen připomínkám.
=> Předěláno skloňování do string template

src/Inkluzitron/Handlers/InviteHandler.cs, src/Inkluzitron/appsettings.json
Aby těch PRs nebylo málo, tak tady je další, Uvítací zpráva do DM.
=> Uvítací zpráva do DM

src/Inkluzitron/Data/BotDatabaseContext.cs, src/Inkluzitron/Data/Entities/Badge.cs, src/Inkluzitron/Data/Entities/User.cs, src/Inkluzitron/Enums/CommandArguments/ConsentType.cs, src/Inkluzitron/Enums/CommandConsent.cs, src/Inkluzitron/Extensions/BotDatabaseContextExtensions.cs, src/Inkluzitron/Migrations/20210702230715_Badges.Designer.cs, src/Inkluzitron/Migrations/20210702230715_Badges.cs, src/Inkluzitron/Modules/Badges/BadgesModule.cs, src/Inkluzitron/Modules/ModuleBase.cs, src/Inkluzitron/Modules/UserModule.cs, src/Inkluzitron/Services/PointsService.cs
* Zobrazení odznaků u bodů
* Zobrazení odznaků na informaci o uživateli
* Consent pro zobrazení odznaků na profilu
* Přejmenován popis consentu na "spicy obrázky"
Pouze pro mody:
* Přidání/smazání odznaku
* Výpis všech odznaků a uživatelů, kteří jej získali
_(obrázek odznaku je jen ilustrační)_
=> Zobrazení odznaků v informaci o uživateli a bodech

src/Inkluzitron/Modules/DuckModule.cs, src/Inkluzitron/appsettings.json
... a taky změněn endpoint v configu na nový (jakože na starý, ale v novém systému, if it makes sense)
Časem to bude asi chtít celé přepsat na nové API, ale to je hóóódně do budoucna
=> Odstraněn hardcodovaný API endpoint isKachnaOpen

src/Inkluzitron/Inkluzitron.csproj
- Aktualizace Unicode knihovny, takže už by bot měl rozumět moderním emojis
=> #139 Oprava nechuti bota ke špenátu
